#!/bin/bash
readonly THIS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "${THIS_DIR}"/.joplin-utils-common

main () {
  local id=$1
  shift
  local fields="${1-}"
  if [[ -n $fields ]]; then
    fields=",$fields"
  fi
  __joplin_utils_api get "resources/$id" "id,title$fields" | jq .
}

main ${1+"$@"}
