#!/bin/bash
readonly THIS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "${THIS_DIR}"/.joplin-utils-common

main () {
  local id=$1
  __joplin_utils_api delete "notes/$id" | jq .
}

main ${1+"$@"}
