#!/bin/bash
readonly THIS_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
source "${THIS_DIR}"/.joplin-utils-common

main () {
  local payload=$1
  __joplin_utils_api create "notes" "$payload" | jq .
}

main ${1+"$@"}
